name: Android 14 6.1
permissions:
  contents: write
on:
  workflow_dispatch:
jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库源码
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 安装编译依赖
        run: |
          sudo apt update -y
          sudo apt install -y build-essential libssl-dev libelf-dev bison flex zip unzip lld llvm python3

      # 直接进入现有嵌套目录编译，不移动文件
      - name: 内核配置编译
        run: |
          cd oneplus/mt6989_v_15.0.2_ace5_race
          export ARCH=arm64
          make oplus_plf110_defconfig
          make -j$(nproc)

      - name: 打包刷机包
        run: |
          mkdir anykernel
          cp oneplus/mt6989_v_15.0.2_ace5_race/arch/arm64/boot/Image anykernel/
          cd anykernel
          zip -r ../kernel.zip Image
          cd ..

      - name: 发布刷机包
        uses: softprops/action-gh-release@v1
        with:
          files: kernel.zip
          tag_name: PLF110-A14-6.1-${{ github.sha }}
          generate_release_notes: true